const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(require.resolve('../index.js'), 'utf8').replace(/^\(\(\) => \{\r?\n'use strict';\r?\n/, '').replace(/\r?\n\}\)\(\);\s*$/, '');
let saves = 0;
const context = { chat: [], chatId: 'mail-test', name1: '小夏', name2: '阿远', extensionSettings: {}, chatMetadata: {}, saveMetadata: async () => {}, saveChat: async () => { saves++; }, addOneMessage: () => {} };
const sandbox = { console, setTimeout, clearTimeout, URL, TextEncoder, Uint8Array, DataView, Blob, AbortController, window: { crypto: {} }, document: { readyState: 'loading', addEventListener() {}, querySelector() { return null; }, querySelectorAll() { return []; } }, SillyTavern: { getContext: () => context, libs: {} }, toastr: { error() {}, success() {}, warning() {}, info() {} } };
vm.createContext(sandbox);
vm.runInContext(source, sandbox);
const run = code => vm.runInContext(code, sandbox);
(async () => {
  assert.equal(run("validMailDate('2025-02-30')"), false);
  assert.equal(run("validMailDate('2024-02-29')"), true);
  assert.equal(run("parseTaggedPage('<page><body>还想对你说').incomplete"), true);
  assert.equal(run("parseTaggedPage('<page><body>完整的结尾。</body></page>').incomplete"), false);
  assert.ok(run('batchOutputBudget({})') >= 10000);
  assert.ok(run('batchOutputBudget({period:{isExtended:true}})') >= 24000);
  sandbox.longRomance = '心里的话。'.repeat(2000) + '这是完整的最后一句。';
  assert.equal(run("parseBatch('<journal_batch><page type=\"romance_diary\" save=\"true\"><body>'+longRomance+'</body></page></journal_batch>').updates[0].page.body"), sandbox.longRomance);
  run("currentBook = blankBook(); currentBookStorageKey = storageKey(); saveSpecificBook = async () => {}; render = () => {}; currentBook.timeline.currentDayKey = 'date:2025-05-01'");
  const mail = run("createScheduledMail(currentBook, {date:'2025-05-03',kind:'card',body:'祝你生日快乐。<b>原文</b>'})");
  assert.equal(run('currentBook.scheduledMail.length'), 1);
  assert.equal(run('createSyncedBookSnapshot(currentBook).scheduledMail.length'), 1);
  context.chat = [{ is_user: true, mes: '2025年5月2日，早安。' }, { is_user: false, mes: '他向我招手。' }];
  await run('checkScheduledMail()');
  assert.equal(saves, 0, '未来信件不能提前寄出');
  context.chat.push({ is_user: true, mes: '两天后，我们又见面了。' }, { is_user: false, mes: '他打开了门。', extra: { reasoning: '一年后' } });
  await Promise.all([run('checkScheduledMail()'), run('checkScheduledMail()')]);
  assert.equal(saves, 1, '跨越预约日期时恰好寄出一次');
  assert.equal(context.chat.at(-1).is_user, true);
  assert.equal(context.chat.at(-1).is_system, false);
  assert.ok(context.chat.at(-1).mes.includes('祝你生日快乐。<b>原文</b>'));
  assert.equal(context.chat.at(-1).extra.privateJournalMailId, mail.id);
  await run('checkScheduledMail()');
  assert.equal(saves, 1, '重复事件不得重复寄信');
  const savedClock = run('JSON.stringify(currentBook.mailClock)');
  run('currentBook = migrateBook(JSON.parse(JSON.stringify(currentBook)))');
  await run('checkScheduledMail()');
  assert.equal(run('JSON.stringify(currentBook.mailClock)'), savedClock, '重载不得再次累计同一相对日期');
  assert.equal(saves, 1, '重载已寄出记录不得重寄');
  const delivered = run('JSON.parse(JSON.stringify(currentBook))');
  sandbox.delivered = delivered;
  assert.equal(run("mergeStoredBooks(delivered, {...delivered, scheduledMail: delivered.scheduledMail.map(m=>({...m,status:'pending',updatedAt:'2099-01-01'}))}).scheduledMail[0].status"), 'sent');
  run("createScheduledMail(currentBook,{date:'2025-05-10',kind:'letter',body:'未寄的情书'}); cancelScheduledMail(currentBook,currentBook.scheduledMail[1].id)");
  assert.equal(run('currentBook.scheduledMail[1].status'), 'cancelled');
  assert.equal(run("mergeStoredBooks(currentBook, {...currentBook, scheduledMail: currentBook.scheduledMail.map(m=>({...m,status:'pending'}))}).scheduledMail[1].status"), 'cancelled');
  // A failed host save must be visible and must reuse the already inserted message.
  run("createScheduledMail(currentBook,{date:'2025-05-01',kind:'letter',body:'失败后重试'});");
  const pending = run('currentBook.scheduledMail[2]');
  context.saveChat = async () => { throw new Error('offline'); };
  await assert.rejects(run(`deliverScheduledMail(currentBook, currentBook.scheduledMail[2])`), /offline/);
  const insertedCount = context.chat.length;
  context.saveChat = async () => { saves++; };
  await run('deliverScheduledMail(currentBook, currentBook.scheduledMail[2])');
  assert.equal(context.chat.length, insertedCount, '保存失败重试不能再插入一封');
  assert.equal(pending.status, 'sent');
  // No host send service: preserve draft and do not claim delivery.
  run("createScheduledMail(currentBook,{date:'2025-05-01',kind:'card',body:'保留这封'});");
  delete context.saveChat;
  await assert.rejects(run('deliverScheduledMail(currentBook,currentBook.scheduledMail[3])'), /保存聊天/);
  assert.equal(run('currentBook.scheduledMail[3].status'), 'pending');
  console.log('Mail and truncation regression tests passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
